import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BCM)
GPIO.setup(14,GPIO.OUT);GPIO.setup(15,GPIO.OUT);GPIO.setup(18,GPIO.OUT)
GPIO.setup(23,GPIO.OUT);GPIO.setup(24,GPIO.OUT);GPIO.setup(25,GPIO.OUT)
GPIO.setup(8,GPIO.OUT) ;GPIO.setup(7,GPIO.OUT) ;GPIO.setup(1,GPIO.OUT)
GPIO.setup(12,GPIO.OUT);GPIO.setup(16,GPIO.OUT);GPIO.setup(20,GPIO.OUT)
GPIO.setup(21,GPIO.OUT);GPIO.setup(2,GPIO.OUT);GPIO.setup(3,GPIO.OUT)
GPIO.setup(4,GPIO.OUT);GPIO.setup(17,GPIO.OUT);GPIO.setup(27,GPIO.OUT)
GPIO.setup(22,GPIO.OUT);GPIO.setup(10,GPIO.OUT);GPIO.setup(9,GPIO.OUT)
GPIO.setup(11,GPIO.OUT);GPIO.setup(8,GPIO.OUT);GPIO.setup(5,GPIO.OUT)
GPIO.setup(6,GPIO.OUT);GPIO.setup(13,GPIO.OUT);GPIO.setup(19,GPIO.OUT)
GPIO.setup(26,GPIO.OUT)
GPIO.cleanup()
